apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:33-apache
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: TZ
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: MYSQL_PASSWORD
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: NEXTCLOUD_ADMIN_USER
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: NEXTCLOUD_ADMIN_PASSWORD
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: NEXTCLOUD_TRUSTED_DOMAINS
            - name: OVERWRITEPROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: OVERWRITEPROTOCOL
          volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: nextcloud-data