apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-secret.yaml
  - 03-configmap.yaml
  - 04-storage.yaml
  - 05-mariadb.yml
  - 06-nextcloud.yaml
  - 07-service.yaml